---
include:
  default:
    - profile::openstack::compute::migration
    - profile::openstack::compute::hypervisor
    - profile::openstack::volume
    - profile::openstack::network
    - profile::logging::rsyslog::client
    - profile::openstack::openrc
  kickstart:
    - profile::base::lvm
    - profile::virtualization::nested
    - profile::network::yum_proxy
    - profile::monitoring::sensu::agent
  bootstrap:
    - profile::base::lvm
    - profile::network::yum_proxy

# Manage default availability zone
profile::openstack::compute::manage_az:            true

profile::base::network::manage_httpproxy: true
profile::network::yum_proxy::yum_proxy:   "http://%{hiera('mgmt__address__proxy')}:8888"

# Source proxy for internet access during puppetrun
#puppet::cron_cmd: "if [ -e /root/proxy.sh ] ; then source /root/proxy.sh ; fi ; \
#  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"
puppet::cron_cmd: "/opt/puppetlabs/bin/puppet agent --config /etc/puppetlabs/puppet/puppet.conf --onetime --no-daemonize"

profile::openstack::compute::migration::enable_nova_account: true
# Set .ssh dir for nova to 0755 to enable sensu checks
profile::openstack::compute::migration::chmod_ssh_dir:       true
# Enable intance migration via ssh
profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0" #FIXME (limit source)
# compute nodes write firewall rules on the fly, thou shalt not purge
profile::base::firewall::purge_firewall: false

openstack_extras::repo::redhat::redhat::manage_rdo: false
profile::base::common::manage_lvm: true

profile::openstack::openrc::password:     "%{hiera('nova_api_password')}"
profile::openstack::openrc::username:     'nova'
profile::openstack::openrc::project_name: 'services'

profile::openstack::network::plugin: calico

profile::base::common::packages:
  'networking-calico': {}
  'python-openstackclient': {}
  'gcc-c++': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

# Sensu (needs gcc-c++)
profile::monitoring::sensu::agent::plugins:
  sensu-plugins-http:
    type:         package
    pkg_version:  '1.0.0'

profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.1.0'
    provider: 'sensu_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'

# metadata api check
profile::monitoring::sensu::agent::checks:
  'metadata-api':
    command:      "check-http.rb -u http://127.0.0.1:8775"
    interval:     60
    subscribers:  ['checks']
  'nova-ssh-key':
    command:      "sudo /opt/sensu/embedded/bin/check-file-exists.rb -f /var/lib/nova/.ssh/id_rsa"
    interval:     60
    subscribers:  ['checks']
  'metrics-disk':
    type:         'metric'
    command:      'metrics-disk-usage.rb --scheme disk.%{::hostname} -f -B G'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

sudo::configs:
  sensu_tty:
    priority:   20
    content:    'Defaults:sensu !requiretty'
  sensu:
    priority:   25
    content:    'sensu ALL = (root) NOPASSWD: /opt/sensu/embedded/bin/check-file-exists.rb -f /var/lib/nova/.ssh/id_rsa'


profile::openstack::compute::hypervisor::fix_snapshot_loc: true # FIXME - Should probably be removed for newton release

calico::compute: true
etcd::mode: 'proxy'

calico::compute::bird_template:  'profile/bird/bird.conf.erb'
calico::compute::bird6_template: 'profile/bird/bird6.conf.erb'

named_interfaces::config:
  mgmt:
    - em3
  transport: #FIXME
    - team1
  trp:
    - team1
  service: #FIXME
    - team1
  live:
    - team1.120

sudo::purge: false

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda3
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
    exclude: 'openstack-neutron openstack-neutron-common python-neutron'
  calico22:
    ensure: present
    exclude: 'calico-dhcp-agent' #FIXME
  ceph-%{hiera('ceph_version')}:
    ensure: present

# Compute nodes need only admin and cinder keys
ceph::profile::params::client_keys:
  'client.admin':
    secret: "%{hiera('client_admin::secret')}"
    mode: '0600'
    user: 'ceph'
    group: 'ceph'
    cap_mon: 'allow *'
    cap_osd: 'allow *'
    cap_mds: 'allow *'
  'client.cinder':
    secret: "%{hiera('client_cinder::secret')}"
    mode: '0600'
    user: 'nova'
    group: 'nova'
    cap_mon: 'allow r'
    cap_osd: 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rwx pool=images'
