---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - bond0
  ceph:
    - bond0

profile::base::common::manage_fake_ssd: true

#profile::base::lvm::physical_volume:
#  '/dev/sda3':
#    ensure: present
#    force:  true
#profile::base::lvm::volume_group:
#  'vg_journala':
#    physical_volumes:
#      - /dev/sda3
#profile::base::lvm::logical_volume:
#  lv_journala01:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala01"

profile::storage::fake_ssds:
  'sdb': {}

ceph::profile::params::osds:
  '/dev/sdb':
    ensure: present
  '/dev/sdc':
    ensure: present
#    db_device: '/dev/sdm'
#    wal_device: '/dev/sdm'
  '/dev/sdd':
    ensure: present
  '/dev/sde':
    ensure: present
  '/dev/sdf':
    ensure: present
  '/dev/sdg':
    ensure: present
  '/dev/sdh':
    ensure: present
  '/dev/sdi':
    ensure: present
  '/dev/sdj':
    ensure: present
  '/dev/sdk':
    ensure: present
  '/dev/sdl':
    ensure: present
#  '/dev/sdm':
#    journal: '/journal/journala11/journal'
#  '/dev/sdn':
#    journal: '/journal/journala12/journal'
#  '/dev/sdo':
#    journal: '/journal/journala13/journal'
#  '/dev/sdp':
#    journal: '/journal/journala14/journal'
#  '/dev/sdq':
#    journal: '/journal/journala15/journal'
