---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - bond1
  ceph:
    - bond1

profile::storage::fake_ssds:
  'sdb': {}
  'sdc': {}

ceph::profile::params::osds:
  '/dev/sdb':
    ensure: present
  '/dev/sdc':
    ensure: present
  '/dev/sdd':
    ensure: present
  '/dev/sde':
    ensure: present
  '/dev/sdf':
    ensure: present
  '/dev/sdg':
    ensure: present
