---
include:
  kickstart:
    - profile::monitoring::sensu::agent

profile::monitoring::sensu::agent::enable_agent:  true

calico::compute::bird_template: 'profile/bird/bird.conf.erb'

ntp::servers:
  - "%{hiera('netcfg_mgmt_netpart')}.100"
  - "%{hiera('netcfg_mgmt_netpart')}.101"

named_interfaces::config:
  mgmt:
    - eth0
  transport:
    - eth0.100
  trp:
    - eth0.100
  live:
    - eth0_100

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'eth0.100':
    'ipaddress': [ '0.0.0.0', '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", "%{hiera('netcfg_trp_gateway')}" ]
    'table':     [ 'private', 'main', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'eth0.100':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]
